#!/bin/bash
git pull

bash reload-projects-script

sudo docker stop gc-services-name
sudo docker rm gc-services-name
sudo docker build -t gc-services .
sudo docker run --name gc-services-name -p 13579:8080 gc-services

