apiVersion: v1
kind: Service
metadata:
  name: beanie-kiosk-service
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    {{- include "app.labels" . | nindent 4 }}
