apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beanie-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "www.fireshellstudio.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: beanie-kiosk-service
            port:
              number: 80
      - path: "/beanie"
        pathType: Prefix
        backend:
          service:
            name: beanie-kiosk-service
            port:
              number: 80
