apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: beanie-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.fireshellstudio.com
    http:
      paths:
      - path: /
        backend:
          serviceName: beanie-kiosk-service
          servicePort: 80
      - path: /beanie/
        backend:
          serviceName: beanie-kiosk-service
          servicePort: 80