apiVersion: v1
kind: Secret
metadata:
  name: bct-fleetinventory-local-secrets
type: Opaque
stringData:
  PERSISTENCE_CONNECTION: "Server={{ .Values.persistence.host }};Port={{ .Values.global.port }};Database={{ .Values.persistence.database }};User id={{ .Values.persistence.user }};Password={{ .Values.persistence.password }};SslMode={{ .Values.persistence.ssl }}"