name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.0.1
      BUILD_CONFIGURATION: Release
      DOCKER_REPO: stephenwike
      SERVICE_DOCKER_IMAGE: beanie-service
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      HELM_CHART_NAME: beanie
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker Login
        run: ./ci/docker-login.ps1
        shell: pwsh
      - name: Install helm
        run: sudo curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Build WebApi
        run: ./ci/build-webapi.ps1
        shell: pwsh
      - name: Publish WebApi
        run: ./ci/publish-webapi.ps1
        shell: pwsh
      - name: Deploy Helm Chart
        run: ./ci/deploy-helm-chart.ps1
        shell: pwsh
