name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.0.1
      BUILD_CONFIGURATION: Release
      DOCKER_REPO: stephenwike
      WEBAPI_DOCKER_IMAGE: beanie-webapi
      UI_DOCKER_IMAGE: beanie-ui
      MIGRATION_DOCKER_IMAGE: beanie-migration
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      HELM_CHART_NAME: beanie
      KUBERNETES_CLUSTER_NAME: scw-k8s
      KUBERNETES_SERVER: ${{secrets.KUBERNETES_SERVER}}
      KUBERNETES_CERTIFICATE: ${{secrets.KUBERNETES_CERTIFICATE}}
      KUBERNETES_CLIENT_CERTIFICATE: ${{secrets.KUBERNETES_CLIENT_CERTIFICATE}}
      KUBERNETES_CLIENT_KEY: ${{secrets.KUBERNETES_CLIENT_KEY}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker Login
        run: ./ci/docker-login.ps1
        shell: pwsh
      - name: Install helm
        run: sudo curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Build WebApi
        run: ./ci/build-webapi.ps1
        shell: pwsh
      - name: Build UI
        run: ./ci/build-ui.ps1
        shell: pwsh
      - name: Build Migration
        run: ./ci/build-migration.ps1
        shell: pwsh
      - name: Publish WebApi
        run: ./ci/publish-webapi.ps1
        shell: pwsh
      - name: Publish UI
        run: ./ci/publish-ui.ps1
        shell: pwsh
      - name: Publish Migration
        run: ./ci/publish-migration.ps1
        shell: pwsh
      - name: Deploy Helm Chart
        run: ./ci/deploy-helm-chart.ps1
        shell: pwsh
